#!/bin/sh
#SBATCH --time=15
hostname
source /opt/intel/oneapi/setvars.sh

mpirun -np 16 -map-by ppr:2:socket -bind-to socket python3 local_methods.py -pl ['n1','n2','n3','tblock1','tblock2','tblock3'] -itm 7 -ts 5
